/*
 * Definancy API
 * REST API for managing asset, network and contract configurations, and vault-based financial operations. This API provides a comprehensive set of endpoints for health monitoring, network management, asset configuration, contract management, vault lifecycle management, and QR-Code generation. It is designed to facilitate seamless integration with financial systems, ensuring secure and efficient payment processing while maintaining strict compliance standards.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@definancy.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.definancy.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.definancy.model.AmountRaw;
import com.definancy.model.AmountValue;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.definancy.JSON;


import javax.ws.rs.core.GenericType;
import javax.ws.rs.core.Response;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;

import com.fasterxml.jackson.core.JsonGenerator;
import com.fasterxml.jackson.core.JsonParser;
import com.fasterxml.jackson.core.JsonProcessingException;
import com.fasterxml.jackson.core.type.TypeReference;
import com.fasterxml.jackson.databind.DeserializationContext;
import com.fasterxml.jackson.databind.JsonMappingException;
import com.fasterxml.jackson.databind.JsonNode;
import com.fasterxml.jackson.databind.SerializerProvider;
import com.fasterxml.jackson.databind.annotation.JsonDeserialize;
import com.fasterxml.jackson.databind.annotation.JsonSerialize;
import com.fasterxml.jackson.databind.deser.std.StdDeserializer;
import com.fasterxml.jackson.databind.ser.std.StdSerializer;
import com.definancy.JSON;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.20.0")
@JsonDeserialize(using=AmountFormat.AmountFormatDeserializer.class)
@JsonSerialize(using = AmountFormat.AmountFormatSerializer.class)
public class AmountFormat extends AbstractOpenApiSchema {
    private static final Logger log = Logger.getLogger(AmountFormat.class.getName());

    public static class AmountFormatSerializer extends StdSerializer<AmountFormat> {
        public AmountFormatSerializer(Class<AmountFormat> t) {
            super(t);
        }

        public AmountFormatSerializer() {
            this(null);
        }

        @Override
        public void serialize(AmountFormat value, JsonGenerator jgen, SerializerProvider provider) throws IOException, JsonProcessingException {
            jgen.writeObject(value.getActualInstance());
        }
    }

    public static class AmountFormatDeserializer extends StdDeserializer<AmountFormat> {
        public AmountFormatDeserializer() {
            this(AmountFormat.class);
        }

        public AmountFormatDeserializer(Class<?> vc) {
            super(vc);
        }

        @Override
        public AmountFormat deserialize(JsonParser jp, DeserializationContext ctxt) throws IOException, JsonProcessingException {
            JsonNode tree = jp.readValueAsTree();

            Object deserialized = null;
            // deserialize AmountValue
            try {
                deserialized = tree.traverse(jp.getCodec()).readValueAs(AmountValue.class);
                AmountFormat ret = new AmountFormat();
                ret.setActualInstance(deserialized);
                return ret;
            } catch (Exception e) {
                // deserialization failed, continue, log to help debugging
                log.log(Level.FINER, "Input data does not match 'AmountFormat'", e);
            }

            // deserialize AmountRaw
            try {
                deserialized = tree.traverse(jp.getCodec()).readValueAs(AmountRaw.class);
                AmountFormat ret = new AmountFormat();
                ret.setActualInstance(deserialized);
                return ret;
            } catch (Exception e) {
                // deserialization failed, continue, log to help debugging
                log.log(Level.FINER, "Input data does not match 'AmountFormat'", e);
            }

            throw new IOException("Failed deserialization for AmountFormat: no match found");
        }

        /**
         * Handle deserialization of the 'null' value.
         */
        @Override
        public AmountFormat getNullValue(DeserializationContext ctxt) throws JsonMappingException {
            throw new JsonMappingException(ctxt.getParser(), "AmountFormat cannot be null");
        }
    }

    // store a list of schema names defined in anyOf
    public static final Map<String, GenericType<?>> schemas = new HashMap<>();

    public AmountFormat() {
        super("anyOf", Boolean.FALSE);
    }

    public AmountFormat(AmountValue o) {
        super("anyOf", Boolean.FALSE);
        setActualInstance(o);
    }

    public AmountFormat(AmountRaw o) {
        super("anyOf", Boolean.FALSE);
        setActualInstance(o);
    }

    static {
        schemas.put("AmountRaw", new GenericType<AmountRaw>() {
        });
        schemas.put("AmountValue", new GenericType<AmountValue>() {
        });
        JSON.registerDescendants(AmountFormat.class, Collections.unmodifiableMap(schemas));
    }

    @Override
    public Map<String, GenericType<?>> getSchemas() {
        return AmountFormat.schemas;
    }

    /**
     * Set the instance that matches the anyOf child schema, check
     * the instance parameter is valid against the anyOf child schemas:
     * AmountRaw, AmountValue
     *
     * It could be an instance of the 'anyOf' schemas.
     * The anyOf child schemas may themselves be a composed schema (allOf, anyOf, anyOf).
     */
    @Override
    public void setActualInstance(Object instance) {
        if (JSON.isInstanceOf(AmountValue.class, instance, new HashSet<>())) {
            super.setActualInstance(instance);
            return;
        }

        if (JSON.isInstanceOf(AmountRaw.class, instance, new HashSet<>())) {
            super.setActualInstance(instance);
            return;
        }

        throw new RuntimeException("Invalid instance type. Must be AmountRaw, AmountValue");
    }

    /**
     * Get the actual instance, which can be the following:
     * AmountRaw, AmountValue
     *
     * @return The actual instance (AmountRaw, AmountValue)
     */
    @Override
    public Object getActualInstance() {
        return super.getActualInstance();
    }

    /**
     * Get the actual instance of `AmountValue`. If the actual instance is not `AmountValue`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `AmountValue`
     * @throws ClassCastException if the instance is not `AmountValue`
     */
    public AmountValue getAmountValue() throws ClassCastException {
        return (AmountValue)super.getActualInstance();
    }

    /**
     * Get the actual instance of `AmountRaw`. If the actual instance is not `AmountRaw`,
     * the ClassCastException will be thrown.
     *
     * @return The actual instance of `AmountRaw`
     * @throws ClassCastException if the instance is not `AmountRaw`
     */
    public AmountRaw getAmountRaw() throws ClassCastException {
        return (AmountRaw)super.getActualInstance();
    }

}

