/*
 * Definancy API
 * REST API for managing asset, network and contract configurations, and vault-based financial operations. This API provides a comprehensive set of endpoints for health monitoring, network management, asset configuration, contract management, vault lifecycle management, and QR-Code generation. It is designed to facilitate seamless integration with financial systems, ensuring secure and efficient payment processing while maintaining strict compliance standards.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@definancy.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.definancy.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.definancy.JSON;


/**
 * Smallest-denomination integer form of an amount paired with the asset&#39;s decimal precision (e.g. raw&#x3D;\&quot;150000000\&quot;, decimals&#x3D;8 for 1.5 BTC). The integer-precise counterpart to AmountValue.
 */
@JsonPropertyOrder({
  AmountRaw.JSON_PROPERTY_RAW,
  AmountRaw.JSON_PROPERTY_DECIMALS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.20.0")
public class AmountRaw {
  public static final String JSON_PROPERTY_RAW = "raw";
  @javax.annotation.Nonnull
  private String raw;

  public static final String JSON_PROPERTY_DECIMALS = "decimals";
  @javax.annotation.Nonnull
  private Integer decimals;

  public AmountRaw() { 
  }

  public AmountRaw raw(@javax.annotation.Nonnull String raw) {
    this.raw = raw;
    return this;
  }

  /**
   * Raw amount value in the smallest unit of the asset (e.g., satoshi for btc).
   * @return raw
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_RAW, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getRaw() {
    return raw;
  }


  @JsonProperty(value = JSON_PROPERTY_RAW, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRaw(@javax.annotation.Nonnull String raw) {
    this.raw = raw;
  }


  public AmountRaw decimals(@javax.annotation.Nonnull Integer decimals) {
    this.decimals = decimals;
    return this;
  }

  /**
   * Number of decimal places to apply when displaying the amount to users.
   * minimum: 0
   * maximum: 77
   * @return decimals
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_DECIMALS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getDecimals() {
    return decimals;
  }


  @JsonProperty(value = JSON_PROPERTY_DECIMALS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setDecimals(@javax.annotation.Nonnull Integer decimals) {
    this.decimals = decimals;
  }


  /**
   * Return true if this AmountRaw object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    AmountRaw amountRaw = (AmountRaw) o;
    return Objects.equals(this.raw, amountRaw.raw) &&
        Objects.equals(this.decimals, amountRaw.decimals);
  }

  @Override
  public int hashCode() {
    return Objects.hash(raw, decimals);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class AmountRaw {\n");
    sb.append("    raw: ").append(toIndentedString(raw)).append("\n");
    sb.append("    decimals: ").append(toIndentedString(decimals)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

