/*
 * Definancy API
 * REST API for managing asset, network and contract configurations, and vault-based financial operations. This API provides a comprehensive set of endpoints for health monitoring, network management, asset configuration, contract management, vault lifecycle management, and QR-Code generation. It is designed to facilitate seamless integration with financial systems, ensuring secure and efficient payment processing while maintaining strict compliance standards.
 *
 * The version of the OpenAPI document: 0.0.1.wip.20250925
 * Contact: support@definancy.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.definancy.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.definancy.JSON;


/**
 * Confirmation progress information for transactions in the confirming state, providing current status and estimated completion time for full confirmation.
 */
@JsonPropertyOrder({
  BlockchainConfirmationStats.JSON_PROPERTY_CONFIRMED,
  BlockchainConfirmationStats.JSON_PROPERTY_REMAINING,
  BlockchainConfirmationStats.JSON_PROPERTY_ETA
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.20.0")
public class BlockchainConfirmationStats {
  public static final String JSON_PROPERTY_CONFIRMED = "confirmed";
  @javax.annotation.Nonnull
  private Integer confirmed;

  public static final String JSON_PROPERTY_REMAINING = "remaining";
  @javax.annotation.Nonnull
  private Integer remaining;

  public static final String JSON_PROPERTY_ETA = "eta";
  @javax.annotation.Nonnull
  private Integer eta;

  public BlockchainConfirmationStats() { 
  }

  public BlockchainConfirmationStats confirmed(@javax.annotation.Nonnull Integer confirmed) {
    this.confirmed = confirmed;
    return this;
  }

  /**
   * Number of confirmations currently observed for this transaction.
   * minimum: 0
   * maximum: 65535
   * @return confirmed
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CONFIRMED, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getConfirmed() {
    return confirmed;
  }


  @JsonProperty(value = JSON_PROPERTY_CONFIRMED, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setConfirmed(@javax.annotation.Nonnull Integer confirmed) {
    this.confirmed = confirmed;
  }


  public BlockchainConfirmationStats remaining(@javax.annotation.Nonnull Integer remaining) {
    this.remaining = remaining;
    return this;
  }

  /**
   * Number of additional confirmations needed to reach required threshold.
   * minimum: 0
   * maximum: 65535
   * @return remaining
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_REMAINING, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getRemaining() {
    return remaining;
  }


  @JsonProperty(value = JSON_PROPERTY_REMAINING, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setRemaining(@javax.annotation.Nonnull Integer remaining) {
    this.remaining = remaining;
  }


  public BlockchainConfirmationStats eta(@javax.annotation.Nonnull Integer eta) {
    this.eta = eta;
    return this;
  }

  /**
   * Estimated timestamp when the transaction will reach full confirmation based on network block time averages.
   * minimum: 0
   * @return eta
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ETA, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getEta() {
    return eta;
  }


  @JsonProperty(value = JSON_PROPERTY_ETA, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setEta(@javax.annotation.Nonnull Integer eta) {
    this.eta = eta;
  }


  /**
   * Return true if this BlockchainConfirmationStats object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    BlockchainConfirmationStats blockchainConfirmationStats = (BlockchainConfirmationStats) o;
    return Objects.equals(this.confirmed, blockchainConfirmationStats.confirmed) &&
        Objects.equals(this.remaining, blockchainConfirmationStats.remaining) &&
        Objects.equals(this.eta, blockchainConfirmationStats.eta);
  }

  @Override
  public int hashCode() {
    return Objects.hash(confirmed, remaining, eta);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class BlockchainConfirmationStats {\n");
    sb.append("    confirmed: ").append(toIndentedString(confirmed)).append("\n");
    sb.append("    remaining: ").append(toIndentedString(remaining)).append("\n");
    sb.append("    eta: ").append(toIndentedString(eta)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

