/*
 * Definancy API
 * REST API for managing asset, network and contract configurations, and vault-based financial operations. This API provides a comprehensive set of endpoints for health monitoring, network management, asset  configuration, contract management, vault lifecycle management, and QR-Code generation. It is designed to facilitate seamless integration with financial systems, ensuring secure and efficient payment  processing while maintaining strict compliance standards.
 *
 * The version of the OpenAPI document: 0.0.1.wip.20250925
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.definancy.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.definancy.model.ComplianceScenario;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.definancy.JSON;


/**
 * Comprehensive compliance status and requirements for payment acceptance.  Tracks document submission requirements and validation status across  all contracts involved in payment processing.
 */
@JsonPropertyOrder({
  Compliance.JSON_PROPERTY_SCENARIOS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.20.0")
public class Compliance {
  public static final String JSON_PROPERTY_SCENARIOS = "scenarios";
  @javax.annotation.Nonnull
  private List<ComplianceScenario> scenarios;

  public Compliance() { 
  }

  public Compliance scenarios(@javax.annotation.Nonnull List<ComplianceScenario> scenarios) {
    this.scenarios = scenarios;
    return this;
  }

  public Compliance addScenariosItem(ComplianceScenario scenariosItem) {
    if (this.scenarios == null) {
      this.scenarios = new ArrayList<>();
    }
    this.scenarios.add(scenariosItem);
    return this;
  }

  /**
   * Contract-specific compliance requirements and current status for  each asset-network combination in the payment acceptance.
   * @return scenarios
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_SCENARIOS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<ComplianceScenario> getScenarios() {
    return scenarios;
  }


  @JsonProperty(value = JSON_PROPERTY_SCENARIOS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setScenarios(@javax.annotation.Nonnull List<ComplianceScenario> scenarios) {
    this.scenarios = scenarios;
  }


  /**
   * Return true if this Compliance object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Compliance compliance = (Compliance) o;
    return Objects.equals(this.scenarios, compliance.scenarios);
  }

  @Override
  public int hashCode() {
    return Objects.hash(scenarios);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Compliance {\n");
    sb.append("    scenarios: ").append(toIndentedString(scenarios)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

