/*
 * Definancy API
 * REST API for managing asset, network and contract configurations, and vault-based financial operations. This API provides a comprehensive set of endpoints for health monitoring, network management, asset  configuration, contract management, vault lifecycle management, and QR-Code generation. It is designed to facilitate seamless integration with financial systems, ensuring secure and efficient payment  processing while maintaining strict compliance standards.
 *
 * The version of the OpenAPI document: 0.0.1.wip.20250925
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.definancy.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.definancy.model.PaymentAcceptancePayTrait;
import com.definancy.model.PaymentAcceptancePriceTrait;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.definancy.JSON;


/**
 * ContractTraits
 */
@JsonPropertyOrder({
  ContractTraits.JSON_PROPERTY_PAYMENT_ACCEPTANCE_PRICE_TRAIT,
  ContractTraits.JSON_PROPERTY_PAYMENT_ACCEPTANCE_PAY_TRAIT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.20.0")
public class ContractTraits {
  public static final String JSON_PROPERTY_PAYMENT_ACCEPTANCE_PRICE_TRAIT = "payment-acceptance-price-trait";
  @javax.annotation.Nullable
  private PaymentAcceptancePriceTrait paymentAcceptancePriceTrait;

  public static final String JSON_PROPERTY_PAYMENT_ACCEPTANCE_PAY_TRAIT = "payment-acceptance-pay-trait";
  @javax.annotation.Nullable
  private PaymentAcceptancePayTrait paymentAcceptancePayTrait;

  public ContractTraits() { 
  }

  public ContractTraits paymentAcceptancePriceTrait(@javax.annotation.Nullable PaymentAcceptancePriceTrait paymentAcceptancePriceTrait) {
    this.paymentAcceptancePriceTrait = paymentAcceptancePriceTrait;
    return this;
  }

  /**
   * Get paymentAcceptancePriceTrait
   * @return paymentAcceptancePriceTrait
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PAYMENT_ACCEPTANCE_PRICE_TRAIT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public PaymentAcceptancePriceTrait getPaymentAcceptancePriceTrait() {
    return paymentAcceptancePriceTrait;
  }


  @JsonProperty(value = JSON_PROPERTY_PAYMENT_ACCEPTANCE_PRICE_TRAIT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPaymentAcceptancePriceTrait(@javax.annotation.Nullable PaymentAcceptancePriceTrait paymentAcceptancePriceTrait) {
    this.paymentAcceptancePriceTrait = paymentAcceptancePriceTrait;
  }


  public ContractTraits paymentAcceptancePayTrait(@javax.annotation.Nullable PaymentAcceptancePayTrait paymentAcceptancePayTrait) {
    this.paymentAcceptancePayTrait = paymentAcceptancePayTrait;
    return this;
  }

  /**
   * Get paymentAcceptancePayTrait
   * @return paymentAcceptancePayTrait
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_PAYMENT_ACCEPTANCE_PAY_TRAIT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public PaymentAcceptancePayTrait getPaymentAcceptancePayTrait() {
    return paymentAcceptancePayTrait;
  }


  @JsonProperty(value = JSON_PROPERTY_PAYMENT_ACCEPTANCE_PAY_TRAIT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setPaymentAcceptancePayTrait(@javax.annotation.Nullable PaymentAcceptancePayTrait paymentAcceptancePayTrait) {
    this.paymentAcceptancePayTrait = paymentAcceptancePayTrait;
  }


  /**
   * Return true if this ContractTraits object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ContractTraits contractTraits = (ContractTraits) o;
    return Objects.equals(this.paymentAcceptancePriceTrait, contractTraits.paymentAcceptancePriceTrait) &&
        Objects.equals(this.paymentAcceptancePayTrait, contractTraits.paymentAcceptancePayTrait);
  }

  @Override
  public int hashCode() {
    return Objects.hash(paymentAcceptancePriceTrait, paymentAcceptancePayTrait);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ContractTraits {\n");
    sb.append("    paymentAcceptancePriceTrait: ").append(toIndentedString(paymentAcceptancePriceTrait)).append("\n");
    sb.append("    paymentAcceptancePayTrait: ").append(toIndentedString(paymentAcceptancePayTrait)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

