/*
 * Definancy API
 * REST API for managing asset, network and contract configurations, and vault-based financial operations. This API provides a comprehensive set of endpoints for health monitoring, network management, asset configuration, contract management, vault lifecycle management, and QR-Code generation. It is designed to facilitate seamless integration with financial systems, ensuring secure and efficient payment processing while maintaining strict compliance standards.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@definancy.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.definancy.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.definancy.model.Amount;
import com.definancy.model.ContractId;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.definancy.JSON;


/**
 * Pairing of a specific contract with a precise amount value. Used in **API responses** to provide complete amount information including both display value and raw precision data.
 */
@JsonPropertyOrder({
  ContractAmount.JSON_PROPERTY_CONTRACT_ID,
  ContractAmount.JSON_PROPERTY_AMOUNT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.20.0")
public class ContractAmount {
  public static final String JSON_PROPERTY_CONTRACT_ID = "contract-id";
  @javax.annotation.Nonnull
  private ContractId contractId;

  public static final String JSON_PROPERTY_AMOUNT = "amount";
  @javax.annotation.Nonnull
  private Amount amount;

  public ContractAmount() { 
  }

  public ContractAmount contractId(@javax.annotation.Nonnull ContractId contractId) {
    this.contractId = contractId;
    return this;
  }

  /**
   * Get contractId
   * @return contractId
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_CONTRACT_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ContractId getContractId() {
    return contractId;
  }


  @JsonProperty(value = JSON_PROPERTY_CONTRACT_ID, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setContractId(@javax.annotation.Nonnull ContractId contractId) {
    this.contractId = contractId;
  }


  public ContractAmount amount(@javax.annotation.Nonnull Amount amount) {
    this.amount = amount;
    return this;
  }

  /**
   * Get amount
   * @return amount
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_AMOUNT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Amount getAmount() {
    return amount;
  }


  @JsonProperty(value = JSON_PROPERTY_AMOUNT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAmount(@javax.annotation.Nonnull Amount amount) {
    this.amount = amount;
  }


  /**
   * Return true if this ContractAmount object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    ContractAmount contractAmount = (ContractAmount) o;
    return Objects.equals(this.contractId, contractAmount.contractId) &&
        Objects.equals(this.amount, contractAmount.amount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(contractId, amount);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class ContractAmount {\n");
    sb.append("    contractId: ").append(toIndentedString(contractId)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

