/*
 * Definancy API
 * REST API for managing asset, network and contract configurations, and vault-based financial operations. This API provides a comprehensive set of endpoints for health monitoring, network management, asset  configuration, contract management, vault lifecycle management, and QR-Code generation. It is designed to facilitate seamless integration with financial systems, ensuring secure and efficient payment  processing while maintaining strict compliance standards.
 *
 * The version of the OpenAPI document: 0.0.1.wip.20250925
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.definancy.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.definancy.model.DocumentStatus;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.definancy.JSON;


/**
 * Document metadata and associations.
 */
@JsonPropertyOrder({
  DocumentInfo.JSON_PROPERTY_VAULT,
  DocumentInfo.JSON_PROPERTY_STATUS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.20.0")
public class DocumentInfo {
  public static final String JSON_PROPERTY_VAULT = "vault";
  @javax.annotation.Nonnull
  private String vault;

  public static final String JSON_PROPERTY_STATUS = "status";
  @javax.annotation.Nonnull
  private DocumentStatus status;

  public DocumentInfo() { 
  }

  public DocumentInfo vault(@javax.annotation.Nonnull String vault) {
    this.vault = vault;
    return this;
  }

  /**
   * Unique vault identifier.
   * @return vault
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_VAULT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getVault() {
    return vault;
  }


  @JsonProperty(value = JSON_PROPERTY_VAULT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setVault(@javax.annotation.Nonnull String vault) {
    this.vault = vault;
  }


  public DocumentInfo status(@javax.annotation.Nonnull DocumentStatus status) {
    this.status = status;
    return this;
  }

  /**
   * Get status
   * @return status
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_STATUS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public DocumentStatus getStatus() {
    return status;
  }


  @JsonProperty(value = JSON_PROPERTY_STATUS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStatus(@javax.annotation.Nonnull DocumentStatus status) {
    this.status = status;
  }


  /**
   * Return true if this DocumentInfo object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    DocumentInfo documentInfo = (DocumentInfo) o;
    return Objects.equals(this.vault, documentInfo.vault) &&
        Objects.equals(this.status, documentInfo.status);
  }

  @Override
  public int hashCode() {
    return Objects.hash(vault, status);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class DocumentInfo {\n");
    sb.append("    vault: ").append(toIndentedString(vault)).append("\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

