/*
 * Definancy API
 * REST API for managing asset, network and contract configurations, and vault-based financial operations. This API provides a comprehensive set of endpoints for health monitoring, network management, asset configuration, contract management, vault lifecycle management, and QR-Code generation. It is designed to facilitate seamless integration with financial systems, ensuring secure and efficient payment processing while maintaining strict compliance standards.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@definancy.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.definancy.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.definancy.JSON;


/**
 * URL templates for a network&#39;s block explorer. Use {value} as a placeholder for the address or transaction ID.
 */
@JsonPropertyOrder({
  NetworkExplorer.JSON_PROPERTY_ADDRESS_URL,
  NetworkExplorer.JSON_PROPERTY_TRANSACTION_URL
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.20.0")
public class NetworkExplorer {
  public static final String JSON_PROPERTY_ADDRESS_URL = "address-url";
  @javax.annotation.Nonnull
  private String addressUrl;

  public static final String JSON_PROPERTY_TRANSACTION_URL = "transaction-url";
  @javax.annotation.Nonnull
  private String transactionUrl;

  public NetworkExplorer() { 
  }

  public NetworkExplorer addressUrl(@javax.annotation.Nonnull String addressUrl) {
    this.addressUrl = addressUrl;
    return this;
  }

  /**
   * URL template for address lookup. Replace {value} with the address.
   * @return addressUrl
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ADDRESS_URL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getAddressUrl() {
    return addressUrl;
  }


  @JsonProperty(value = JSON_PROPERTY_ADDRESS_URL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAddressUrl(@javax.annotation.Nonnull String addressUrl) {
    this.addressUrl = addressUrl;
  }


  public NetworkExplorer transactionUrl(@javax.annotation.Nonnull String transactionUrl) {
    this.transactionUrl = transactionUrl;
    return this;
  }

  /**
   * URL template for transaction lookup. Replace {value} with the transaction ID.
   * @return transactionUrl
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TRANSACTION_URL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getTransactionUrl() {
    return transactionUrl;
  }


  @JsonProperty(value = JSON_PROPERTY_TRANSACTION_URL, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setTransactionUrl(@javax.annotation.Nonnull String transactionUrl) {
    this.transactionUrl = transactionUrl;
  }


  /**
   * Return true if this NetworkExplorer object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    NetworkExplorer networkExplorer = (NetworkExplorer) o;
    return Objects.equals(this.addressUrl, networkExplorer.addressUrl) &&
        Objects.equals(this.transactionUrl, networkExplorer.transactionUrl);
  }

  @Override
  public int hashCode() {
    return Objects.hash(addressUrl, transactionUrl);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class NetworkExplorer {\n");
    sb.append("    addressUrl: ").append(toIndentedString(addressUrl)).append("\n");
    sb.append("    transactionUrl: ").append(toIndentedString(transactionUrl)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

