/*
 * Definancy API
 * REST API for managing asset, network and contract configurations, and vault-based financial operations. This API provides a comprehensive set of endpoints for health monitoring, network management, asset  configuration, contract management, vault lifecycle management, and QR-Code generation. It is designed to facilitate seamless integration with financial systems, ensuring secure and efficient payment  processing while maintaining strict compliance standards.
 *
 * The version of the OpenAPI document: 0.0.1.wip.20250925
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.definancy.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.definancy.model.Amount;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.definancy.JSON;


/**
 * PaymentAcceptancePayTrait
 */
@JsonPropertyOrder({
  PaymentAcceptancePayTrait.JSON_PROPERTY_MIN_AMOUNT,
  PaymentAcceptancePayTrait.JSON_PROPERTY_MAX_AMOUNT
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.20.0")
public class PaymentAcceptancePayTrait {
  public static final String JSON_PROPERTY_MIN_AMOUNT = "min-amount";
  @javax.annotation.Nullable
  private Amount minAmount;

  public static final String JSON_PROPERTY_MAX_AMOUNT = "max-amount";
  @javax.annotation.Nullable
  private Amount maxAmount;

  public PaymentAcceptancePayTrait() { 
  }

  public PaymentAcceptancePayTrait minAmount(@javax.annotation.Nullable Amount minAmount) {
    this.minAmount = minAmount;
    return this;
  }

  /**
   * Get minAmount
   * @return minAmount
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MIN_AMOUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Amount getMinAmount() {
    return minAmount;
  }


  @JsonProperty(value = JSON_PROPERTY_MIN_AMOUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMinAmount(@javax.annotation.Nullable Amount minAmount) {
    this.minAmount = minAmount;
  }


  public PaymentAcceptancePayTrait maxAmount(@javax.annotation.Nullable Amount maxAmount) {
    this.maxAmount = maxAmount;
    return this;
  }

  /**
   * Get maxAmount
   * @return maxAmount
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_MAX_AMOUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Amount getMaxAmount() {
    return maxAmount;
  }


  @JsonProperty(value = JSON_PROPERTY_MAX_AMOUNT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setMaxAmount(@javax.annotation.Nullable Amount maxAmount) {
    this.maxAmount = maxAmount;
  }


  /**
   * Return true if this PaymentAcceptancePayTrait object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PaymentAcceptancePayTrait paymentAcceptancePayTrait = (PaymentAcceptancePayTrait) o;
    return Objects.equals(this.minAmount, paymentAcceptancePayTrait.minAmount) &&
        Objects.equals(this.maxAmount, paymentAcceptancePayTrait.maxAmount);
  }

  @Override
  public int hashCode() {
    return Objects.hash(minAmount, maxAmount);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PaymentAcceptancePayTrait {\n");
    sb.append("    minAmount: ").append(toIndentedString(minAmount)).append("\n");
    sb.append("    maxAmount: ").append(toIndentedString(maxAmount)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

