/*
 * Definancy API
 * REST API for managing asset, network and contract configurations, and vault-based financial operations. This API provides a comprehensive set of endpoints for health monitoring, network management, asset configuration, contract management, vault lifecycle management, and QR-Code generation. It is designed to facilitate seamless integration with financial systems, ensuring secure and efficient payment processing while maintaining strict compliance standards.
 *
 * The version of the OpenAPI document: 0.0.1.wip.20250925
 * Contact: support@definancy.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.definancy.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.definancy.model.PaymentAcceptanceOrder;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import java.util.UUID;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.definancy.JSON;


/**
 * Base configuration for payment acceptance operations containing optional commercial context and document associations. Serves as the foundation for both request and response payment acceptance structures.
 */
@JsonPropertyOrder({
  PaymentAcceptanceConfigBase.JSON_PROPERTY_ORDER,
  PaymentAcceptanceConfigBase.JSON_PROPERTY_DOCUMENTS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.20.0")
public class PaymentAcceptanceConfigBase {
  public static final String JSON_PROPERTY_ORDER = "order";
  @javax.annotation.Nullable
  private PaymentAcceptanceOrder order;

  public static final String JSON_PROPERTY_DOCUMENTS = "documents";
  @javax.annotation.Nullable
  private List<UUID> documents;

  public PaymentAcceptanceConfigBase() { 
  }

  public PaymentAcceptanceConfigBase order(@javax.annotation.Nullable PaymentAcceptanceOrder order) {
    this.order = order;
    return this;
  }

  /**
   * Get order
   * @return order
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ORDER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public PaymentAcceptanceOrder getOrder() {
    return order;
  }


  @JsonProperty(value = JSON_PROPERTY_ORDER, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setOrder(@javax.annotation.Nullable PaymentAcceptanceOrder order) {
    this.order = order;
  }


  public PaymentAcceptanceConfigBase documents(@javax.annotation.Nullable List<UUID> documents) {
    this.documents = documents;
    return this;
  }

  public PaymentAcceptanceConfigBase addDocumentsItem(UUID documentsItem) {
    if (this.documents == null) {
      this.documents = new ArrayList<>();
    }
    this.documents.add(documentsItem);
    return this;
  }

  /**
   * Optional list of document IDs to associate with this payment  acceptance for compliance purposes.
   * @return documents
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_DOCUMENTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<UUID> getDocuments() {
    return documents;
  }


  @JsonProperty(value = JSON_PROPERTY_DOCUMENTS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setDocuments(@javax.annotation.Nullable List<UUID> documents) {
    this.documents = documents;
  }


  /**
   * Return true if this PaymentAcceptanceConfigBase object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PaymentAcceptanceConfigBase paymentAcceptanceConfigBase = (PaymentAcceptanceConfigBase) o;
    return Objects.equals(this.order, paymentAcceptanceConfigBase.order) &&
        Objects.equals(this.documents, paymentAcceptanceConfigBase.documents);
  }

  @Override
  public int hashCode() {
    return Objects.hash(order, documents);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PaymentAcceptanceConfigBase {\n");
    sb.append("    order: ").append(toIndentedString(order)).append("\n");
    sb.append("    documents: ").append(toIndentedString(documents)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

