/*
 * Definancy API
 * REST API for managing asset, network and contract configurations, and vault-based financial operations. This API provides a comprehensive set of endpoints for health monitoring, network management, asset configuration, contract management, vault lifecycle management, and QR-Code generation. It is designed to facilitate seamless integration with financial systems, ensuring secure and efficient payment processing while maintaining strict compliance standards.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@definancy.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.definancy.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.definancy.model.Compliance;
import com.definancy.model.PaymentAcceptanceScenario;
import com.definancy.model.PaymentAcceptanceStatus;
import com.definancy.model.VelocityWarning;
import com.definancy.model.Version;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.definancy.JSON;


/**
 * Payment acceptance operational state and lifecycle information. Contains  current processing status, payment scenarios, compliance state, and  version tracking for audit and monitoring purposes.
 */
@JsonPropertyOrder({
  PaymentAcceptanceInfo.JSON_PROPERTY_STATUS,
  PaymentAcceptanceInfo.JSON_PROPERTY_VERSION,
  PaymentAcceptanceInfo.JSON_PROPERTY_SCENARIOS,
  PaymentAcceptanceInfo.JSON_PROPERTY_COMPLIANCE,
  PaymentAcceptanceInfo.JSON_PROPERTY_WARNINGS
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.20.0")
public class PaymentAcceptanceInfo {
  public static final String JSON_PROPERTY_STATUS = "status";
  @javax.annotation.Nonnull
  private PaymentAcceptanceStatus status;

  public static final String JSON_PROPERTY_VERSION = "version";
  @javax.annotation.Nonnull
  private Version version;

  public static final String JSON_PROPERTY_SCENARIOS = "scenarios";
  @javax.annotation.Nonnull
  private List<PaymentAcceptanceScenario> scenarios;

  public static final String JSON_PROPERTY_COMPLIANCE = "compliance";
  @javax.annotation.Nonnull
  private Compliance compliance;

  public static final String JSON_PROPERTY_WARNINGS = "warnings";
  @javax.annotation.Nullable
  private List<VelocityWarning> warnings;

  public PaymentAcceptanceInfo() { 
  }

  public PaymentAcceptanceInfo status(@javax.annotation.Nonnull PaymentAcceptanceStatus status) {
    this.status = status;
    return this;
  }

  /**
   * Current processing state of the payment acceptance.
   * @return status
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_STATUS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public PaymentAcceptanceStatus getStatus() {
    return status;
  }


  @JsonProperty(value = JSON_PROPERTY_STATUS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setStatus(@javax.annotation.Nonnull PaymentAcceptanceStatus status) {
    this.status = status;
  }


  public PaymentAcceptanceInfo version(@javax.annotation.Nonnull Version version) {
    this.version = version;
    return this;
  }

  /**
   * Version tracking information for audit and synchronization purposes.
   * @return version
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_VERSION, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Version getVersion() {
    return version;
  }


  @JsonProperty(value = JSON_PROPERTY_VERSION, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setVersion(@javax.annotation.Nonnull Version version) {
    this.version = version;
  }


  public PaymentAcceptanceInfo scenarios(@javax.annotation.Nonnull List<PaymentAcceptanceScenario> scenarios) {
    this.scenarios = scenarios;
    return this;
  }

  public PaymentAcceptanceInfo addScenariosItem(PaymentAcceptanceScenario scenariosItem) {
    if (this.scenarios == null) {
      this.scenarios = new ArrayList<>();
    }
    this.scenarios.add(scenariosItem);
    return this;
  }

  /**
   * Active payment execution scenarios with blockchain addresses,  amounts, and transaction tracking information.
   * @return scenarios
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_SCENARIOS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public List<PaymentAcceptanceScenario> getScenarios() {
    return scenarios;
  }


  @JsonProperty(value = JSON_PROPERTY_SCENARIOS, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setScenarios(@javax.annotation.Nonnull List<PaymentAcceptanceScenario> scenarios) {
    this.scenarios = scenarios;
  }


  public PaymentAcceptanceInfo compliance(@javax.annotation.Nonnull Compliance compliance) {
    this.compliance = compliance;
    return this;
  }

  /**
   * Current compliance status and requirements for all contracts in this payment acceptance.
   * @return compliance
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_COMPLIANCE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Compliance getCompliance() {
    return compliance;
  }


  @JsonProperty(value = JSON_PROPERTY_COMPLIANCE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setCompliance(@javax.annotation.Nonnull Compliance compliance) {
    this.compliance = compliance;
  }


  public PaymentAcceptanceInfo warnings(@javax.annotation.Nullable List<VelocityWarning> warnings) {
    this.warnings = warnings;
    return this;
  }

  public PaymentAcceptanceInfo addWarningsItem(VelocityWarning warningsItem) {
    if (this.warnings == null) {
      this.warnings = new ArrayList<>();
    }
    this.warnings.add(warningsItem);
    return this;
  }

  /**
   * Velocity warnings that fired during the payment creation check. Present only when warn-mode limits were exceeded.
   * @return warnings
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_WARNINGS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public List<VelocityWarning> getWarnings() {
    return warnings;
  }


  @JsonProperty(value = JSON_PROPERTY_WARNINGS, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setWarnings(@javax.annotation.Nullable List<VelocityWarning> warnings) {
    this.warnings = warnings;
  }


  /**
   * Return true if this PaymentAcceptanceInfo object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PaymentAcceptanceInfo paymentAcceptanceInfo = (PaymentAcceptanceInfo) o;
    return Objects.equals(this.status, paymentAcceptanceInfo.status) &&
        Objects.equals(this.version, paymentAcceptanceInfo.version) &&
        Objects.equals(this.scenarios, paymentAcceptanceInfo.scenarios) &&
        Objects.equals(this.compliance, paymentAcceptanceInfo.compliance) &&
        Objects.equals(this.warnings, paymentAcceptanceInfo.warnings);
  }

  @Override
  public int hashCode() {
    return Objects.hash(status, version, scenarios, compliance, warnings);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PaymentAcceptanceInfo {\n");
    sb.append("    status: ").append(toIndentedString(status)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("    scenarios: ").append(toIndentedString(scenarios)).append("\n");
    sb.append("    compliance: ").append(toIndentedString(compliance)).append("\n");
    sb.append("    warnings: ").append(toIndentedString(warnings)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

