/*
 * Definancy API
 * REST API for managing asset, network and contract configurations, and vault-based financial operations. This API provides a comprehensive set of endpoints for health monitoring, network management, asset configuration, contract management, vault lifecycle management, and QR-Code generation. It is designed to facilitate seamless integration with financial systems, ensuring secure and efficient payment processing while maintaining strict compliance standards.
 *
 * The version of the OpenAPI document: 0.0.1.wip.20250925
 * Contact: support@definancy.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.definancy.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.definancy.model.PersonLegalIdType;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.definancy.JSON;


/**
 * Business registration and identification information for legal entities.  Contains official registration details required for entity verification  and compliance with business identification regulations.
 */
@JsonPropertyOrder({
  PersonLegalId.JSON_PROPERTY_NUMBER,
  PersonLegalId.JSON_PROPERTY_TYPE,
  PersonLegalId.JSON_PROPERTY_ISSUER
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.20.0")
public class PersonLegalId {
  public static final String JSON_PROPERTY_NUMBER = "number";
  @javax.annotation.Nonnull
  private String number;

  public static final String JSON_PROPERTY_TYPE = "type";
  @javax.annotation.Nonnull
  private PersonLegalIdType type;

  public static final String JSON_PROPERTY_ISSUER = "issuer";
  @javax.annotation.Nonnull
  private String issuer;

  public PersonLegalId() { 
  }

  public PersonLegalId number(@javax.annotation.Nonnull String number) {
    this.number = number;
    return this;
  }

  /**
   * Official business registration number, tax identification number, or  other government-issued entity identifier exactly as it appears on  official documentation.
   * @return number
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_NUMBER, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getNumber() {
    return number;
  }


  @JsonProperty(value = JSON_PROPERTY_NUMBER, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setNumber(@javax.annotation.Nonnull String number) {
    this.number = number;
  }


  public PersonLegalId type(@javax.annotation.Nonnull PersonLegalIdType type) {
    this.type = type;
    return this;
  }

  /**
   * Get type
   * @return type
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public PersonLegalIdType getType() {
    return type;
  }


  @JsonProperty(value = JSON_PROPERTY_TYPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setType(@javax.annotation.Nonnull PersonLegalIdType type) {
    this.type = type;
  }


  public PersonLegalId issuer(@javax.annotation.Nonnull String issuer) {
    this.issuer = issuer;
    return this;
  }

  /**
   * Government authority, tax agency, or business registration office  that issued the legal entity identification. Used for verification  and authenticity validation purposes.
   * @return issuer
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_ISSUER, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public String getIssuer() {
    return issuer;
  }


  @JsonProperty(value = JSON_PROPERTY_ISSUER, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setIssuer(@javax.annotation.Nonnull String issuer) {
    this.issuer = issuer;
  }


  /**
   * Return true if this PersonLegalId object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    PersonLegalId personLegalId = (PersonLegalId) o;
    return Objects.equals(this.number, personLegalId.number) &&
        Objects.equals(this.type, personLegalId.type) &&
        Objects.equals(this.issuer, personLegalId.issuer);
  }

  @Override
  public int hashCode() {
    return Objects.hash(number, type, issuer);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class PersonLegalId {\n");
    sb.append("    number: ").append(toIndentedString(number)).append("\n");
    sb.append("    type: ").append(toIndentedString(type)).append("\n");
    sb.append("    issuer: ").append(toIndentedString(issuer)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

