/*
 * Definancy API
 * REST API for managing asset, network and contract configurations, and vault-based financial operations. This API provides a comprehensive set of endpoints for health monitoring, network management, asset configuration, contract management, vault lifecycle management, and QR-Code generation. It is designed to facilitate seamless integration with financial systems, ensuring secure and efficient payment processing while maintaining strict compliance standards.
 *
 * The version of the OpenAPI document: 0.1.0
 * Contact: support@definancy.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.definancy.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.definancy.model.Version;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.definancy.JSON;


/**
 * Vault lifecycle metadata.
 */
@JsonPropertyOrder({
  VaultInfo.JSON_PROPERTY_ARCHIVED_AT,
  VaultInfo.JSON_PROPERTY_VERSION
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.20.0")
public class VaultInfo {
  public static final String JSON_PROPERTY_ARCHIVED_AT = "archived-at";
  @javax.annotation.Nullable
  private Integer archivedAt;

  public static final String JSON_PROPERTY_VERSION = "version";
  @javax.annotation.Nonnull
  private Version version;

  public VaultInfo() { 
  }

  public VaultInfo archivedAt(@javax.annotation.Nullable Integer archivedAt) {
    this.archivedAt = archivedAt;
    return this;
  }

  /**
   * Timestamp of vault archival (null if active).
   * minimum: 0
   * @return archivedAt
   */
  @javax.annotation.Nullable
  @JsonProperty(value = JSON_PROPERTY_ARCHIVED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)

  public Integer getArchivedAt() {
    return archivedAt;
  }


  @JsonProperty(value = JSON_PROPERTY_ARCHIVED_AT, required = false)
  @JsonInclude(value = JsonInclude.Include.USE_DEFAULTS)
  public void setArchivedAt(@javax.annotation.Nullable Integer archivedAt) {
    this.archivedAt = archivedAt;
  }


  public VaultInfo version(@javax.annotation.Nonnull Version version) {
    this.version = version;
    return this;
  }

  /**
   * Get version
   * @return version
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_VERSION, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Version getVersion() {
    return version;
  }


  @JsonProperty(value = JSON_PROPERTY_VERSION, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setVersion(@javax.annotation.Nonnull Version version) {
    this.version = version;
  }


  /**
   * Return true if this VaultInfo object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VaultInfo vaultInfo = (VaultInfo) o;
    return Objects.equals(this.archivedAt, vaultInfo.archivedAt) &&
        Objects.equals(this.version, vaultInfo.version);
  }

  @Override
  public int hashCode() {
    return Objects.hash(archivedAt, version);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VaultInfo {\n");
    sb.append("    archivedAt: ").append(toIndentedString(archivedAt)).append("\n");
    sb.append("    version: ").append(toIndentedString(version)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

