/*
 * Definancy API
 * REST API for managing asset, network and contract configurations, and vault-based financial operations. This API provides a comprehensive set of endpoints for health monitoring, network management, asset  configuration, contract management, vault lifecycle management, and QR-Code generation. It is designed to facilitate seamless integration with financial systems, ensuring secure and efficient payment  processing while maintaining strict compliance standards.
 *
 * The version of the OpenAPI document: 0.0.1.wip.20250925
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.definancy.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.definancy.model.Amount;
import com.definancy.model.ContractAmount;
import com.definancy.model.VelocityScope;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.definancy.JSON;


/**
 * Emitted in the response of estimate/create endpoints when a warn-mode velocity limit is exceeded but the request was still allowed to proceed.
 */
@JsonPropertyOrder({
  VelocityWarning.JSON_PROPERTY_SCOPE,
  VelocityWarning.JSON_PROPERTY_WINDOW_MINUTES,
  VelocityWarning.JSON_PROPERTY_LIMIT,
  VelocityWarning.JSON_PROPERTY_USED
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.20.0")
public class VelocityWarning {
  public static final String JSON_PROPERTY_SCOPE = "scope";
  @javax.annotation.Nonnull
  private VelocityScope scope;

  public static final String JSON_PROPERTY_WINDOW_MINUTES = "window-minutes";
  @javax.annotation.Nonnull
  private Integer windowMinutes;

  public static final String JSON_PROPERTY_LIMIT = "limit";
  @javax.annotation.Nonnull
  private ContractAmount limit;

  public static final String JSON_PROPERTY_USED = "used";
  @javax.annotation.Nonnull
  private Amount used;

  public VelocityWarning() { 
  }

  public VelocityWarning scope(@javax.annotation.Nonnull VelocityScope scope) {
    this.scope = scope;
    return this;
  }

  /**
   * Get scope
   * @return scope
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_SCOPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public VelocityScope getScope() {
    return scope;
  }


  @JsonProperty(value = JSON_PROPERTY_SCOPE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setScope(@javax.annotation.Nonnull VelocityScope scope) {
    this.scope = scope;
  }


  public VelocityWarning windowMinutes(@javax.annotation.Nonnull Integer windowMinutes) {
    this.windowMinutes = windowMinutes;
    return this;
  }

  /**
   * Get windowMinutes
   * minimum: 0
   * @return windowMinutes
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_WINDOW_MINUTES, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getWindowMinutes() {
    return windowMinutes;
  }


  @JsonProperty(value = JSON_PROPERTY_WINDOW_MINUTES, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setWindowMinutes(@javax.annotation.Nonnull Integer windowMinutes) {
    this.windowMinutes = windowMinutes;
  }


  public VelocityWarning limit(@javax.annotation.Nonnull ContractAmount limit) {
    this.limit = limit;
    return this;
  }

  /**
   * Get limit
   * @return limit
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_LIMIT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ContractAmount getLimit() {
    return limit;
  }


  @JsonProperty(value = JSON_PROPERTY_LIMIT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setLimit(@javax.annotation.Nonnull ContractAmount limit) {
    this.limit = limit;
  }


  public VelocityWarning used(@javax.annotation.Nonnull Amount used) {
    this.used = used;
    return this;
  }

  /**
   * Get used
   * @return used
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_USED, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Amount getUsed() {
    return used;
  }


  @JsonProperty(value = JSON_PROPERTY_USED, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setUsed(@javax.annotation.Nonnull Amount used) {
    this.used = used;
  }


  /**
   * Return true if this VelocityWarning object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VelocityWarning velocityWarning = (VelocityWarning) o;
    return Objects.equals(this.scope, velocityWarning.scope) &&
        Objects.equals(this.windowMinutes, velocityWarning.windowMinutes) &&
        Objects.equals(this.limit, velocityWarning.limit) &&
        Objects.equals(this.used, velocityWarning.used);
  }

  @Override
  public int hashCode() {
    return Objects.hash(scope, windowMinutes, limit, used);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VelocityWarning {\n");
    sb.append("    scope: ").append(toIndentedString(scope)).append("\n");
    sb.append("    windowMinutes: ").append(toIndentedString(windowMinutes)).append("\n");
    sb.append("    limit: ").append(toIndentedString(limit)).append("\n");
    sb.append("    used: ").append(toIndentedString(used)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

