/*
 * Definancy API
 * REST API for managing asset, network and contract configurations, and vault-based financial operations. This API provides a comprehensive set of endpoints for health monitoring, network management, asset configuration, contract management, vault lifecycle management, and QR-Code generation. It is designed to facilitate seamless integration with financial systems, ensuring secure and efficient payment processing while maintaining strict compliance standards.
 *
 * The version of the OpenAPI document: 0.0.1.wip.20250925
 * Contact: support@definancy.com
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.definancy.model;

import java.util.Objects;
import java.util.Map;
import java.util.HashMap;
import com.definancy.model.ContractAmountFormat;
import com.definancy.model.VelocityMode;
import com.fasterxml.jackson.annotation.JsonInclude;
import com.fasterxml.jackson.annotation.JsonProperty;
import com.fasterxml.jackson.annotation.JsonCreator;
import com.fasterxml.jackson.annotation.JsonTypeName;
import com.fasterxml.jackson.annotation.JsonValue;
import java.util.Arrays;
import com.fasterxml.jackson.annotation.JsonPropertyOrder;
import com.definancy.JSON;


/**
 * Velocity limit configuration. The unique key per scope is &#x60;windowMinutes&#x60;. Set &#x60;windowMinutes&#x60; to 0 for \&quot;single payment cap\&quot; — no time aggregation; the check compares the requested amount alone against the limit. The limit&#39;s &#x60;amount&#x60; may be denominated in any contract; at check time it is converted to the account&#39;s velocity reference contract via a market quote.
 */
@JsonPropertyOrder({
  VelocityLimitFormat.JSON_PROPERTY_WINDOW_MINUTES,
  VelocityLimitFormat.JSON_PROPERTY_AMOUNT,
  VelocityLimitFormat.JSON_PROPERTY_MODE
})
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.20.0")
public class VelocityLimitFormat {
  public static final String JSON_PROPERTY_WINDOW_MINUTES = "window-minutes";
  @javax.annotation.Nonnull
  private Integer windowMinutes;

  public static final String JSON_PROPERTY_AMOUNT = "amount";
  @javax.annotation.Nonnull
  private ContractAmountFormat amount;

  public static final String JSON_PROPERTY_MODE = "mode";
  @javax.annotation.Nonnull
  private VelocityMode mode;

  public VelocityLimitFormat() { 
  }

  public VelocityLimitFormat windowMinutes(@javax.annotation.Nonnull Integer windowMinutes) {
    this.windowMinutes = windowMinutes;
    return this;
  }

  /**
   * Rolling window length in minutes. 0 means single payment cap.
   * minimum: 0
   * @return windowMinutes
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_WINDOW_MINUTES, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public Integer getWindowMinutes() {
    return windowMinutes;
  }


  @JsonProperty(value = JSON_PROPERTY_WINDOW_MINUTES, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setWindowMinutes(@javax.annotation.Nonnull Integer windowMinutes) {
    this.windowMinutes = windowMinutes;
  }


  public VelocityLimitFormat amount(@javax.annotation.Nonnull ContractAmountFormat amount) {
    this.amount = amount;
    return this;
  }

  /**
   * Get amount
   * @return amount
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_AMOUNT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public ContractAmountFormat getAmount() {
    return amount;
  }


  @JsonProperty(value = JSON_PROPERTY_AMOUNT, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setAmount(@javax.annotation.Nonnull ContractAmountFormat amount) {
    this.amount = amount;
  }


  public VelocityLimitFormat mode(@javax.annotation.Nonnull VelocityMode mode) {
    this.mode = mode;
    return this;
  }

  /**
   * Get mode
   * @return mode
   */
  @javax.annotation.Nonnull
  @JsonProperty(value = JSON_PROPERTY_MODE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)

  public VelocityMode getMode() {
    return mode;
  }


  @JsonProperty(value = JSON_PROPERTY_MODE, required = true)
  @JsonInclude(value = JsonInclude.Include.ALWAYS)
  public void setMode(@javax.annotation.Nonnull VelocityMode mode) {
    this.mode = mode;
  }


  /**
   * Return true if this VelocityLimitFormat object is equal to o.
   */
  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    VelocityLimitFormat velocityLimitFormat = (VelocityLimitFormat) o;
    return Objects.equals(this.windowMinutes, velocityLimitFormat.windowMinutes) &&
        Objects.equals(this.amount, velocityLimitFormat.amount) &&
        Objects.equals(this.mode, velocityLimitFormat.mode);
  }

  @Override
  public int hashCode() {
    return Objects.hash(windowMinutes, amount, mode);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class VelocityLimitFormat {\n");
    sb.append("    windowMinutes: ").append(toIndentedString(windowMinutes)).append("\n");
    sb.append("    amount: ").append(toIndentedString(amount)).append("\n");
    sb.append("    mode: ").append(toIndentedString(mode)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

