package com.definancy.api;

import com.definancy.ApiException;
import com.definancy.ApiClient;
import com.definancy.ApiResponse;
import com.definancy.Configuration;
import com.definancy.Pair;

import javax.ws.rs.core.GenericType;

import com.definancy.model.ErrorList;

import java.util.ArrayList;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;

@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", comments = "Generator version: 7.20.0")
public class AuthApi {
  private ApiClient apiClient;

  public AuthApi() {
    this(Configuration.getDefaultApiClient());
  }

  public AuthApi(ApiClient apiClient) {
    this.apiClient = apiClient;
  }

  /**
   * Get the API client
   *
   * @return API client
   */
  public ApiClient getApiClient() {
    return apiClient;
  }

  /**
   * Set the API client
   *
   * @param apiClient an instance of API client
   */
  public void setApiClient(ApiClient apiClient) {
    this.apiClient = apiClient;
  }

  /**
   * Register a Definancy ID
   * Registers a **Definancy ID**.  This operation does not create a new Definancy ID from scratch but formally registers the Definancy method-specific identifier on the network, enabling it to be resolved and used for verifiable credentials and interactions.
   * @param definancyId The Definancy Identifier. This is a base32-encoded (without padding) string derived from an ED25519 public key. The identifier is generated by: 1. Taking the 32-byte public key 2. Computing a SHA512/256 hash (32 bytes) of the public key 3. Taking the last 4 bytes of this hash as a checksum 4. Appending the checksum to the public key (creating a 36-byte value) 5. Encoding the combined value using base32 without padding (required)
   * @throws ApiException if fails to make API call
   * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
       <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
       <tr><td> 200 </td><td> **Success.** The Definancy ID &#x60;{definancyId}&#x60; was successfully registered. </td><td>  * Cache-Control -  <br>  </td></tr>
       <tr><td> 400 </td><td> The request contains malformed data, invalid parameters, or violates API constraints. This includes validation errors, incorrect data types, missing required fields, or values outside acceptable ranges. Check the error details for specific issues. </td><td>  -  </td></tr>
       <tr><td> 401 </td><td> Authentication credentials are missing, invalid, or expired. The request lacks proper authorization headers or tokens. Clients should verify their authentication setup and ensure valid credentials are provided in subsequent requests. </td><td>  -  </td></tr>
       <tr><td> 403 </td><td> The authenticated user lacks sufficient permissions to perform this operation. While authentication was successful, the user&#39;s role or access level does not permit the requested action. Contact an administrator for access rights. </td><td>  -  </td></tr>
       <tr><td> 409 </td><td> The request could not be completed because the target resource already exists. This typically occurs when attempting to create a resource that duplicates an existing one, such as a duplicate identifier or a resource that violates uniqueness constraints. </td><td>  -  </td></tr>
       <tr><td> 0 </td><td> An unexpected server error occurred while processing the request. This indicates an internal system issue that prevented successful completion. The error details may provide additional context for debugging and support purposes. </td><td>  -  </td></tr>
     </table>
   */
  public void registerAuth(@javax.annotation.Nonnull String definancyId) throws ApiException {
    registerAuthWithHttpInfo(definancyId);
  }

  /**
   * Register a Definancy ID
   * Registers a **Definancy ID**.  This operation does not create a new Definancy ID from scratch but formally registers the Definancy method-specific identifier on the network, enabling it to be resolved and used for verifiable credentials and interactions.
   * @param definancyId The Definancy Identifier. This is a base32-encoded (without padding) string derived from an ED25519 public key. The identifier is generated by: 1. Taking the 32-byte public key 2. Computing a SHA512/256 hash (32 bytes) of the public key 3. Taking the last 4 bytes of this hash as a checksum 4. Appending the checksum to the public key (creating a 36-byte value) 5. Encoding the combined value using base32 without padding (required)
   * @return ApiResponse&lt;Void&gt;
   * @throws ApiException if fails to make API call
   * @http.response.details
     <table border="1">
       <caption>Response Details</caption>
       <tr><td> Status Code </td><td> Description </td><td> Response Headers </td></tr>
       <tr><td> 200 </td><td> **Success.** The Definancy ID &#x60;{definancyId}&#x60; was successfully registered. </td><td>  * Cache-Control -  <br>  </td></tr>
       <tr><td> 400 </td><td> The request contains malformed data, invalid parameters, or violates API constraints. This includes validation errors, incorrect data types, missing required fields, or values outside acceptable ranges. Check the error details for specific issues. </td><td>  -  </td></tr>
       <tr><td> 401 </td><td> Authentication credentials are missing, invalid, or expired. The request lacks proper authorization headers or tokens. Clients should verify their authentication setup and ensure valid credentials are provided in subsequent requests. </td><td>  -  </td></tr>
       <tr><td> 403 </td><td> The authenticated user lacks sufficient permissions to perform this operation. While authentication was successful, the user&#39;s role or access level does not permit the requested action. Contact an administrator for access rights. </td><td>  -  </td></tr>
       <tr><td> 409 </td><td> The request could not be completed because the target resource already exists. This typically occurs when attempting to create a resource that duplicates an existing one, such as a duplicate identifier or a resource that violates uniqueness constraints. </td><td>  -  </td></tr>
       <tr><td> 0 </td><td> An unexpected server error occurred while processing the request. This indicates an internal system issue that prevented successful completion. The error details may provide additional context for debugging and support purposes. </td><td>  -  </td></tr>
     </table>
   */
  public ApiResponse<Void> registerAuthWithHttpInfo(@javax.annotation.Nonnull String definancyId) throws ApiException {
    // Check required parameters
    if (definancyId == null) {
      throw new ApiException(400, "Missing the required parameter 'definancyId' when calling registerAuth");
    }

    // Path parameters
    String localVarPath = "/v1/auth/{definancyId}"
            .replaceAll("\\{definancyId}", apiClient.escapeString(definancyId.toString()));

    String localVarAccept = apiClient.selectHeaderAccept("application/json");
    String localVarContentType = apiClient.selectHeaderContentType();
    String[] localVarAuthNames = new String[] {"dpop-auth", "dpop-proof"};
    return apiClient.invokeAPI("AuthApi.registerAuth", localVarPath, "PUT", new ArrayList<>(), null,
                               new LinkedHashMap<>(), new LinkedHashMap<>(), new LinkedHashMap<>(), localVarAccept, localVarContentType,
                               localVarAuthNames, null, false);
  }
}
